### ISSUE TITLE
Fix the Angular startup code

### ISSUE THREAD

**Issue by radion** [laurho/codeu_project_2017#10]
I couldn’t fully get the Angular app running. Running on a mac and following your instructions (with the additions described above as well)
1. On the master branch, I get an error: `src/app/chat-screen.component.ts(175,49): error TS2339: Property 'model' does not exist on type 'ChatScreenComponent'.` I think this is fixed in pull request #3
2. After manually resolving 1, ran into an issue where it wouldn’t load: `Uncaught ReferenceError: System is not defined`. See screenshot at: https://docs.google.com/document/d/1gr8iJIQXsEaPUm7Zt0p4ECn4Y88zP8XobbJlEGB0Hfw/edit#heading=h.trgxmqy651qo

**Comment by rubanh** [comment]
These should be addressed/fixed but I'll wait to close until others confirm

**Comment by laurho** [comment]
A single client does now load with the current set of instructions✅
