### ISSUE TITLE
Verify TestRunner contains all relevant tests

### ISSUE THREAD

**Issue by radion** [laurho/codeu_project_2017#5]
TestRunner.java contains a list of classes to run: https://github.com/laurho/codeu_project_2017/blob/master/test/codeu/chat/TestRunner.java
Ensure any new testing add (like the PasswordGeneraterTest) is added here. Otherwise, the tests won’t get run.

**Comment by laurho** [comment]
Testing setup changed so that "mvn package" will now run all of the tests!
