### ISSUE TITLE
Cleanup Readme

### ISSUE THREAD

**Issue by radion** [laurho/codeu_project_2017#6]
Need to cleanup the main readme overall.
* Remove unnecessary bits like “Ruban’s Readme Additions”
* Merge the `Getting Started` section with the Angular additions. And clearly document that there’s two types of clients now.
* Simplify mvn installation instructions. (brew install maven for mac, sudo apt-get install maven for Ubuntu)
* It’s somewhat confusing that there’s your own Readme and the official Angular readme - it makes it unclear which to actually follow

**Comment by laurho** [comment]
README cleaned to hopefully a more clear cut of instructions and information about the application.
