### ISSUE TITLE
Fix documentation for Angular setup

### ISSUE THREAD

**Issue by radion** [laurho/codeu_project_2017#8]
The instructions in https://github.com/laurho/codeu_project_2017#to-buildrun-angular2-code were not enough for me to get the project set up. The steps I had to do before npm start:
* Need a package.json file. npm init does this
* These packages are a dependency. Either add them to the package.json file or provide instructions how to install these globally: `typescript` `concurrently` `lite-server`

**Comment by laurho** [comment]
Documentation is now in the README:)
